admins/urls.py
from django.urls import path
from . import views

app_name = 'admins_'

urlpatterns = [
    path('', views.admin_login_check, name='admin_login_check'),
    path('users_list/', views.users_list, name='users_list'),
    path('admin_home/', views.admin_home, name='admin_home'),
    path('activate_user/<str:id>', views.activate_user, name='activate_user')

]

crop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.home, name='index'),

    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_login_check/', include('users.urls')),

    path('admin_login/', views.admin_login, name='admin_login'),
    path('admin_login_check/', include('admins.urls')),
]

templates/admins/admin_base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="shortcut icon" href="{% static 'images/favicon/crop.png' %}" type="image/x-icon">

    <!-- Css Link-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>
        {% block title %}{% endblock %}
    </title>

    <style>
        a {
            color: white
        }

        .bg-light1 {
            background: #1b4670;
            color: White;

        }

        .btn:not(:disabled):not(.disabled) {
            background-color: #1b4670;

        }

        * {
            font-family: "Book Antiqua";
        }
    </style>


</head>
<body style="background:#E9ECEF;">
<!-- Navbar -->
<header>
    <nav class="navbar navbar-expand-lg fixed-top  bg-light1">

        <a class="navbar-brand" href="#">
            <img src="{% static 'images/crop.png' %}" alt="" width="10%" style="margin-top: -10px;">
            <span class="name pull-left">  Admin </span>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/"> Home </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admins_:users_list' %}">Users</a>
                </li>

                <!--<li class="nav-item mr-2">
                    <a class="nav-link" href="#">Pre-Process </a>
                </li>-->

            </ul>

            <button class="btn btn-outline-info my-2 my-sm-0" type="submit">
                <a href="{% url 'admin_login' %}">Logout</a>
            </button>

        </div>
    </nav>
</header>

{% block content %}

{% endblock %}


<!-- Footer -->

<footer class="page-footer font-small  bg-light1">
    <div class="footer-copyright text-center py-3">© 2022 Copyright:
        <a href="#"> CROP</a>
    </div>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/admins/admin_home.html
{% extends 'admins/admin_base.html' %}
{% block title %}
    Admin || Home
{% endblock %}
{% block content %}
    {% load static %}


    <p class="breadcrumb" style="height: 55px; ">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">
            <span style="color: red;">Admin Logged in ❕</span>
        </li>
    </ol>
    </p>
    <section>

        <div class="jumbotron">

            <div class="container">
                <div class="row">
                    <div class="col-md-7">
                        <h1>
                            Intelligent Crop Recommendation System
                            using Machine Learning
                        </h1>
                        <p>
                            The proposed system helps the farmers to
                            choose the right crop by providing insights that
                            ordinary farmers don't keep track of thereby
                            decreasing the chances of crop failure and
                            increasing productivity
                        </p>
                        <button type="button" class="btn btn-primary btn-lg ">
                            <a href="#headingOne1" class="text-white"> Learn More</a>
                        </button>

                    </div>
                    <div class="col-md-5">
                        <img src="{% static 'images/bg-hero.jpg' %}" class="img-fluid" alt="Responsive image">
                    </div>
                </div>

            </div>


        </div>

    </section>


    <!-- Accordion -->
    <section style="font-family: 'Book Antiqua'; text-align: justify; margin-top: -10rem;">


        <div class="jumbotron" style="margin-bottom: -100px;">
            <h1 style="text-align: center; font-family: 'Book Antiqua';"> About Project</h1>
            <div class="container">

                <!--Accordion wrapper-->
                <div class="accordion md-accordion" id="accordionEx" role="tablist" aria-multiselectable="true">

                    <!-- Accordion card -->
                    <div class="card">

                        <!-- Card header -->

                        <div class="card-header btn" role="tab" id="headingOne1">
                            <a data-toggle="collapse" data-parent="#accordionEx" href="#collapseOne1"
                               aria-expanded="true"
                               aria-controls="collapseOne1">
                                <h5 class="mb-0 btn btn-primary">
                                    Abstract &Darr; <i class="fas fa-angle-down rotate-icon"></i>
                                </h5>
                            </a>
                        </div>

                        <!-- Card body -->
                        <div id="collapseOne1" class="collapse show" role="tabpanel" aria-labelledby="headingOne1"
                             data-parent="#accordionEx">
                            <div class="card-body">
                                Agriculture plays a vital role in the socioeconomic fabric of India. Failure of
                                farmers
                                to decide
                                on the best-suited crop for the land using
                                traditional and non-scientific methods is a serious
                                issue for a country where approximately 58 percent
                                of the population is involved in farming. Sometimes
                                farmers were failed to choose the right crops based on
                                the soil conditions, sowing season, and geographical
                                location. This results in suicide, quitting the agriculture
                                field, moving towards urban areas for livelihood. To
                                overcome this issue, this research work has proposed a
                                system to assist the farmers in crop selection by
                                considering all the factors like sowing season, soil, and
                                geographical location. Furthermore, precision
                                agriculture is being implemented with a modern
                                agricultural technology and it is evolving in developing
                                countries that concentrates on site-specific crop
                                management.

                            </div>
                        </div>

                    </div>
                    <!-- Accordion card -->

                    <!-- Accordion card -->
                    <div class="card">

                        <!-- Card header -->
                        <div class="card-header btn" role="tab" id="headingTwo2">
                            <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx"
                               href="#collapseTwo2"
                               aria-expanded="false" aria-controls="collapseTwo2">
                                <h5 class="mb-0 btn btn-primary">
                                    Keywords &Darr; <i class="fas fa-angle-down rotate-icon"></i>
                                </h5>
                            </a>
                        </div>

                        <!-- Card body -->
                        <div id="collapseTwo2" class="collapse" role="tabpanel" aria-labelledby="headingTwo2"
                             data-parent="#accordionEx">
                            <div class="card-body">
                                <ul>
                                    <li>Agriculture</li>
                                    <li>Crop Recommendation,</li>
                                    <li>Machine Learning</li>
                                </ul>
                            </div>
                        </div>

                    </div>
                    <!-- Accordion card -->

                    <!-- Accordion card -->
                    <div class="card">

                        <!-- Card header -->
                        <div class="card-header btn" role="tab" id="headingThree3">
                            <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx"
                               href="#collapseThree3"
                               aria-expanded="false" aria-controls="collapseThree3">
                                <h5 class="mb-0 btn btn-primary">
                                    Conclusion &Darr; <i class="fas fa-angle-down rotate-icon"></i>
                                </h5>
                            </a>
                        </div>

                        <!-- Card body -->
                        <div id="collapseThree3" class="collapse" role="tabpanel" aria-labelledby="headingThree3"
                             data-parent="#accordionEx">
                            <div class="card-body">
                                The proposed system helps the farmers to
                                choose the right crop by providing insights that
                                ordinary farmers don't keep track of thereby
                                decreasing the chances of crop failure and
                                increasing productivity. It also prevents them from
                                incurring losses. In the future, it has been planned
                                to incorporate a web interface as well as a mobile
                                app to provide the recommendations of crop
                                cultivation to the farmers can be accessed by
                                millions of farmers across the country.
                            </div>
                        </div>

                    </div>
                    <!-- Accordion card -->

                </div>

            </div>
            <p style="margin-top: 150px;">

            </p>
            <!-- Accordion -->
        </div>

    </section>


{% endblock %}


templates/admins/users_list.html
{% extends 'admins/admin_base.html' %}

{% block title %}
    User's List
{% endblock %}


{% block content %}
    <style>
        .container {
            font-family: "Book Antiqua";

        }
    </style>

    {% load static %}
    <div class="container">
        <div class="row">
            <div class="col">
                <table class="table table-striped table-hover" style="margin-top: 10rem;">
                    <caption align="top" style="text-align: center;font-size: 2rem;">User List</caption>
                    <thead class="">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Username</th>
                        <th scope="col">Email</th>
                        <th scope="col">Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users_list %}
                        <tr>
                            <th scope="row">{{ forloop.counter0|add:users_list.start_index }}</th>
                            <td>{{ user.name }}</td>
                            <td>{{ user.username }}</td>
                            <td>{{ user.email }}</td>
                            <td>
                                <a href="{% url 'admins_:activate_user' user.id %}" class=" btn btn-link text-white">
                                    {{ user.status }}
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <!-- Pagination-->
                <div class="container p-4">
                    <div class="pagination justify-content-center">
                    <span class="step-links">
                        {% if users_list.has_previous %}
                            <a href="?page=1">&laquo; first </a>
                            <a href="?page={{ users_list.previous_page_number }}"> previous &nbsp;</a>
                        {% endif %}
                    </span>
                        <span class="current">
                        Page{{ users_list.number }}  of  {{ users_list.paginator.num_pages }}
                            &nbsp;
                    </span>

                        {% if users_list.has_next %}
                            <a href="?page={{ users_list.next_page_number }}"> next &nbsp; </a>
                            <a href="?page={{ users_list.paginator.num_pages }}"> last &raquo;</a>
                        {% endif %}
                    </div>
                </div>
                <!-- end of Pagination -->

            </div>

        </div>
    </div>





{% endblock %}

