crop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.home, name='index'),

    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_login_check/', include('users.urls')),

    path('admin_login/', views.admin_login, name='admin_login'),
    path('admin_login_check/', include('admins.urls')),
]

users/urls.py
from django.urls import path
from . import views
app_name = 'users_'

urlpatterns = [
    path('user_register_action/', views.user_register_action, name='user_register_action'),
    path('', views.user_login_check, name='user_login_check'),
    path('add_data/', views.add_data, name='add_data'),
    path('crop_prediction/', views.crop_prediction, name='crop_prediction'),
    path('fertilizer',views.fertilizer,name='fertilizer'),
    path('raw_district_wise_yield_data',views.raw_district_wise_yield_data,name='raw_district_wise_yield_data'),
    # path('ML_Result',views.ML_Result,name="ML_Result"),
    path('view_data',views.view_data,name="view_data"),
    path('crop_recommendation',views.crop_recommendation,name='crop_recommendation'),
    path('crop_sustainability3',views.crop_sustainability3,name="crop_sustainability3"),
    path('user_classification',views.user_classification,name='user_classification'),
    path('plotting',views.plotting,name='plotting'),
    path('predict_ML',views.predict_ML,name='predict_ML'),
    #path('input',views.input,name='input'),

]

users/models.py
from django.db import models


# Create your models here.
class UserRegistrationModel(models.Model):
    name = models.CharField(max_length=100)
    username = models.CharField(unique=True, max_length=100)
    password = models.CharField(max_length=100)
    email = models.CharField(unique=True, max_length=100)

    status = models.CharField(max_length=100, default="waiting")

    def __str__(self):
        return str(self.username)

    class Meta:
        db_table = 'UserRegistrations'

users/forms.py
from django import forms
from .models import UserRegistrationModel


class UserRegistrationForm(forms.ModelForm):
    name = forms.CharField(required=True,
                           max_length=100,
                           widget=forms.TextInput(
                               attrs={
                                   'class': 'form-control',

                               }
                           ))
    username = forms.CharField(required=True,
                               max_length=100,
                               widget=forms.TextInput(
                                   attrs={
                                       'class': 'form-control'
                                   }
                               ))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'class': 'form-control',

        }
    ))
    status = forms.CharField(
        initial='waiting',
        widget=forms.HiddenInput(
            attrs={
                'class': 'form-control'
            }
        ))

    password = forms.CharField(required=True,
                               widget=forms.PasswordInput(
                                   attrs={
                                       'pattern': '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}',
                                       'title': 'Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters',
                                       'class': 'form-control',
                                   }
                               ))

    class Meta:
        model = UserRegistrationModel
        fields = '__all__'



class UserLoginForm(forms.Form):
    username = forms.CharField(required=True,
                               label_suffix='',
                               max_length=100,
                               widget=forms.TextInput(
                                   attrs={
                                       'class': 'form-control'
                                   }
                               ))

    password = forms.CharField(required=True,
                               label_suffix= "",
                               widget=forms.PasswordInput(
                                   attrs={
                                       'pattern': '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}',
                                       'title': 'Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters',
                                       'class': 'form-control',
                                   }
                               ))

users/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib import messages
from django.template import RequestContext

from users.forms import (UserLoginForm, UserRegistrationForm)
from users.models import UserRegistrationModel


# Create your views here.
def user_login_check(request):
    context = {'form': UserLoginForm()}
    if request.method == 'POST':
        print('=000=' * 40, request.POST)
        form = UserLoginForm(request.POST)
        print('VALID:', form.is_valid())
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            print('UserName:', username)
            print('Password:', password)
            try:
                user = UserRegistrationModel.objects.get(username=username, password=password)
                print("User Object", user.status)
                status = user.status
                if status == 'activated':
                    request.session['username'] = user.username
                    request.session['password'] = user.password
                    return render(request, 'users/user_home.html')
                else:
                    messages.success(request, 'Your A/C has not been activated by admin.')
                    return render(request, 'user_login.html', context)
            except Exception as e:
                print("Got Exception: ", e)
                pass
            messages.error(request, 'Invalid username or password.')
    context = {'form': UserLoginForm()}
    return render(request, 'user_login.html', context)


def user_register_action(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your request has been submitted, Admin will get back to you soon.')
            context = {"form": UserRegistrationForm()}
            return render(request, 'register.html', context)
        else:
            messages.error(request, 'Email Already Exists.')

    context = {
        'form': UserRegistrationForm()
    }
    return render(request, 'register.html', context)


def add_data(request):
    return render(request, 'users/add_data.html')


def crop_prediction(request):
    if request.method == 'POST':
        N = request.POST.get('nitrogen')
        P = request.POST.get('Phosphorous')
        K = request.POST.get('Pottasium')
        ph = request.POST.get('ph')
        rainfall = request.POST.get('Rainfall')


def fertilizer(request):
    import pandas as pd
    import os
    from django.conf import settings
    path = os.path.join(settings.MEDIA_ROOT, 'fertilizer.csv')
    df = pd.read_csv(path)
    df = df[['Crop', 'N', 'P', 'K', 'pH', 'soil_moisture']]
    df = df.head(96).to_html
    return render(request, 'users/fertilizer.html', {'dat': df})


def raw_district_wise_yield_data(request):
    import pandas as pd
    import os
    from django.conf import settings
    path = os.path.join(settings.MEDIA_ROOT, 'raw_districtwise_yield_data.csv')
    pf = pd.read_csv(path)
    pf = pf[['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Crop', 'Area', 'Production']]
    pf = pf.head(240).to_html
    return render(request, 'users/raw_district_wise_yield_data.html', {'da': pf})


# def ML_Result(request):
#     return render(request, 'users/ML_Result.html')


def fertilizer(request):
    import pandas as pd
    import os
    from django.conf import settings
    path = os.path.join(settings.MEDIA_ROOT, 'fertilizer.csv')
    df = pd.read_csv(path)
    df = df[['Crop', 'N', 'P', 'K', 'pH', 'soil_moisture']]
    df = df.head(96).to_html
    return render(request, 'users/fertilizer.html', {'dat': df})


def view_data(request):
    return render(request, 'users/view_data.html', {})


def crop_recommendation(request):
    import pandas as pd
    import os
    from django.conf import settings
    path = os.path.join(settings.MEDIA_ROOT, 'crop_recommendation.csv')
    df = pd.read_csv(path)
    df = df[['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'CEC', 'label']]
    df = df.head(2250).to_html
    return render(request, 'users/crop_recommendation.html', {'dat': df})


def crop_sustainability3(request):
    import pandas as pd
    import os
    from django.conf import settings
    path = os.path.join(settings.MEDIA_ROOT, 'crop_sustainability3.csv')
    pf = pd.read_csv(path)
    pf = pf[['N', 'Phosphorous', 'Potassium', 'Ph', 'Soil_Moisture', 'CEC', 'SEASON', 'Suitable_Label']]
    pf = pf.head(2500).to_html
    return render(request, 'users/crop_sustainability3.html', {'da': pf})


def user_classification(request):
    from .utility import process_classification
    dt_accuracy, dt_precission, dt_f1_score, dt_recall = process_classification.build_decisiontree_model()
    nb_accuracy, nb_precission, nb_f1_score, nb_recall = process_classification.build_naive_model()
    svm_accuracy, svm_precission, svm_f1_score, svm_recall = process_classification.build_svm_model()
    lr_accuracy, lr_precission, lr_f1_score, lr_recall = process_classification.build_lregression_model()
    rf_accuracy, rf_precission, rf_f1_score, rf_recall = process_classification.build_random_model()
    # xgb_accuracy, xgb_precission, xgb_f1_score, xgb_recall = process_classification.build_xgboost_model()
    mlp_accuracy, mlp_precission, mlp_f1_score, mlp_recall = process_classification.build_neuralnetwork_model()

    dt = {'dt_accuracy': dt_accuracy, 'dt_precission': dt_precission, 'dt_f1_score': dt_f1_score,
          'dt_recall': dt_recall}
    nb = {'nb_accuracy': nb_accuracy, 'nb_precission': nb_precission, 'nb_f1_score': nb_f1_score,
          'nb_recall': nb_recall}
    svm = {'svm_accuracy': svm_accuracy, 'svm_precission': svm_precission, 'svm_f1_score': svm_f1_score,
           'svm_recall': svm_recall}
    lr = {'lr_accuracy': lr_accuracy, 'lr_precission': lr_precission, 'lr_f1_score': lr_f1_score,
          'lr_recall': lr_recall}
    rf = {'rf_accuracy': rf_accuracy, 'rf_precission': rf_precission, 'rf_f1_score': rf_f1_score,
          'rf_recall': rf_recall}
    # xgb = {'xgb_accuracy': xgb_accuracy, 'xgb_precission': xgb_precission, 'xgb_f1_score': xgb_f1_score,
    #    'xgb_recall': xgb_recall}
    mlp = {'mlp_accuracy': mlp_accuracy, 'mlp_precission': mlp_precission, 'mlp_f1_score': mlp_f1_score,
           'mlp_recall': mlp_recall}
    return render(request, 'users/Ml_result.html', {'dt': dt, 'nb': nb, 'svm': svm, 'lr': lr, 'rf': rf, 'mlp': mlp})


# def user_neuralnetwork(request):
#     from .utility import process_dl
#     accuracy, precission, f1_score, recall = process_dl.build_neural_model()
#     mlp = {'accuracy': accuracy, 'precission': precission, 'f1_score': f1_score, 'recall': recall}
#     return render(request, 'users/Ml_result.html', {'mlp': mlp})


def plotting(request):
    # import matplotlib.pyplot as plt
    # import seaborn as sns
    # from .utility.process_classification import plotting
    # plt.figure(figsize=[10, 6], dpi=100)
    # plt.title('Accuracy Comparision Chart')
    # plt.xlabel('Algorithms')
    # plt.ylabel('Accuracy')
    # pf = sns.barplot(x=plotting.acc, y=plotting().model, palette='dark')
    from .utility.process_classification import plotting
    ll = plotting()
    return render(request, 'users/plotting.html', {'ll': ll})


def predict_ML(request):
    if request.method == "POST":
        n = request.POST.get("nitrogen")
        p = request.POST.get("phosphorous")
        k = request.POST.get("pottasium")
        ph = request.POST.get("ph")
        r = request.POST.get("rainfall")
        import numpy as np
        import pandas as pd
        from .utility.process_classification import build_neuralnetwork_model2
        # path = 'C:\\Users\\Rajesh\\Desktop\\dataset\\crop_recommendation.csv'
        # df = pd.read_csv(path)
        data = np.array([[n, p, k, ph, r]])
        result = build_neuralnetwork_model2(data)
        return render(request, "users/add_data.html", {"result": result})
    else:
        msg = print("Your Field Not Suitable for any Crop,Try with Newer Fields")
        return render(request, "users/add_data.html", {'msg': msg})

# def input(request):
#     return HttpResponse("Hiii")

templates/users/Ml_result.html
{% extends 'users/user_base.html' %}
{% block title %}
User|| Ml_result
{% endblock %}
{% block Ml_result %}
    active
{% endblock %}

{% block content %}
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}


</style>
<section id="intro">

    <div class="intro-text">
        <!--        <div class="container" style="margin-top:-200px;">-->
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br><br/><br>
        <p>
        <h3 align="center" style="color:green;font-weight:bold;">Machine learning Regression algorithm Results</h3></p>
        <!--<a href="#about" class="btn-get-started scrollto">Get Started</a>-->
        <center>

            <table class="table">
                <tr>
                    <th>S.NO</th>
                    <th>Algorithm</th>
                    <th>accuracy</th>
                    <th>precission</th>
                    <th>f1_score</th>
                    <th>recall</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Decision Tree</td>
                    <td>{{dt.dt_accuracy}}</td>
                    <td>{{dt.dt_precission}}</td>
                    <td>{{dt.dt_f1_score}}</td>
                    <td>{{dt.dt_recall}}</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Naive Bayes</td>
                    <td>{{nb.nb_accuracy}}</td>
                    <td>{{nb.nb_precission}}</td>
                    <td>{{nb.nb_f1_score}}</td>
                    <td>{{nb.nb_recall}}</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>SVM</td>
                    <td>{{svm.svm_accuracy}}</td>
                    <td>{{svm.svm_precission}}</td>
                    <td>{{svm.svm_f1_score}}</td>
                    <td>{{svm.svm_recall}}</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>Logistic Regression</td>
                    <td>{{lr.lr_accuracy}}</td>
                    <td>{{lr.lr_precission}}</td>
                    <td>{{lr.lr_f1_score}}</td>
                    <td>{{lr.lr_recall}}</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>Random Forest</td>
                    <td>{{rf.rf_accuracy}}</td>
                    <td>{{rf.rf_precission}}</td>
                    <td>{{rf.rf_f1_score}}</td>
                    <td>{{rf.rf_recall}}</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>Neural Network</td>
                    <td>{{mlp.mlp_accuracy}}</td>
                    <td>{{mlp.mlp_precission}}</td>
                    <td>{{mlp.mlp_f1_score}}</td>
                    <td>{{mlp.mlp_recall}}</td>
                </tr>
            </table>
            </form>
        </center>

    </div>
</section>


<section id="second">

    <div>
<!--        <div class="container" style="margin-top:-200px;">-->
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br><br/><br/>
      <p><h3 align="center" style="color:green;font-weight:bold;"><a target='_self' href="{% url 'users_:plotting' %}" style="color:blue;font-weight:bold;">Algorithm Accuracy Chart</a></h3></p>
      <!--<a href="#about" class="btn-get-started scrollto">Get Started</a>-->
        <center>
        {{ll|safe}}
            </center>
    </div>
  </section>
{% endblock %}

templates/users/add_data.html
{% extends 'users/user_base.html' %}
{% block title %}
User|| Add Data
{% endblock %}
{% block add_data %}
active
{% endblock %}

{% block content %}
<style>


        html body {
            background-color: rgb(206, 206, 228);

        }




</style>
<!--Form Section-->
<br/><br/>
<h2 class="mt-4" style="text-align: center; margin: 0px; color: black">
    <b>Find out the most suitable crop to grow in your farm</b>
</h2>
<br/>
<div style="border-radius: 5%">
    <div style=" width: 350px; height: 50rem; margin: 0px auto; color: black; border-radius: 25px;padding: 10px 10px;">
        <form method="POST" action="{% url 'users_:predict_ML' %}">{% csrf_token %}
            <div class="form-group">
                <label for="Nitrogen" style="font-size: 17px"><b>Nitrogen</b></label>
                <input type="number" class="form-control" id="Nitrogen" name="nitrogen"
                       placeholder="Enter the value (below 99)" style="font-weight: bold" required/>
            </div>
            <div class="form-group">
                <label for="Phosphorous" style="font-size: 17px"><b>Phosphorous</b></label>
                <input type="number" class="form-control" id="Phosphorous" name="phosphorous"
                       placeholder="Enter the value (below 99)" style="font-weight: bold" required/>
            </div>

            <div class="form-group">
                <label for="Pottasium" style="font-size: 17px"><b>Pottasium</b></label>
                <input type="number" class="form-control" id="Pottasium" name="pottasium"
                       placeholder="Enter the value (below 99)" style="font-weight: bold" required/>
            </div>
            <div class="form-group">
                <label for="Rainfall" style="font-size: 17px"><b>Rainfall (in mm)</b></label>
                <input type="number" step="0.01" class="form-control" id="Rainfall" name="rainfall"
                       placeholder="Enter float value(below 230)" style="font-weight: bold" required/>
            </div>
            <div class="form-group">
                <label for="ph" style="font-size: 17px"><b>ph level</b></label>
                <input type="number" step="0.01" class="form-control" id="ph" name="ph"
                       placeholder="Enter float value(below 7.5)"
                       style="font-weight: bold" required/>
            </div>
            <div class="form-group">
                <label for="State" style="font-size: 17px "><b>State</b></label>
                <select onchange="print_city('state', this.selectedIndex);" id="sts" name="stt"
                        class="form-control" style="font-weight: bold; color: black" required="">
                    <option value="">Select State</option>
                    <option value="Andaman &amp; Nicobar">Andaman &amp; Nicobar</option>
                    <option value="Andhra Pradesh">Andhra Pradesh</option>
                    <option value="Arunachal Pradesh">Arunachal Pradesh</option>
                    <option value="Assam">Assam</option>
                    <option value="Bihar">Bihar</option>
                    <option value="Chandigarh">Chandigarh</option>
                    <option value="Chhattisgarh">Chhattisgarh</option>
                    <option value="Dadra &amp; Nagar Haveli">Dadra &amp; Nagar Haveli</option>
                    <option value="Daman &amp; Diu">Daman &amp; Diu</option>
                    <option value="Delhi">Delhi</option>
                    <option value="Goa">Goa</option>
                    <option value="Gujarat">Gujarat</option>
                    <option value="Haryana">Haryana</option>
                    <option value="Himachal Pradesh">Himachal Pradesh</option>
                    <option value="Jammu &amp; Kashmir">Jammu &amp; Kashmir</option>
                    <option value="Jharkhand">Jharkhand</option>
                    <option value="Karnataka">Karnataka</option>
                    <option value="Kerala">Kerala</option>
                    <option value="Lakshadweep">Lakshadweep</option>
                    <option value="Madhya Pradesh">Madhya Pradesh</option>
                    <option value="Maharashtra">Maharashtra</option>
                    <option value="Manipur">Manipur</option>
                    <option value="Meghalaya">Meghalaya</option>
                    <option value="Mizoram">Mizoram</option>
                    <option value="Nagaland">Nagaland</option>
                    <option value="Orissa">Orissa</option>
                    <option value="Pondicherry">Pondicherry</option>
                    <option value="Punjab">Punjab</option>
                    <option value="Rajasthan">Rajasthan</option>
                    <option value="Sikkim">Sikkim</option>
                    <option value="Tamil Nadu">Tamil Nadu</option>
                    <option value="Tripura">Tripura</option>
                    <option value="Uttar Pradesh">Uttar Pradesh</option>
                    <option value="Uttaranchal">Uttaranchal</option>
                    <option value="West Bengal">West Bengal</option>
                </select>
                <br/>
                <script language="javascript">
                        print_state("sts");


                </script>
            </div>

            <div class="d-flex justify-content-center">
                <button
                        type="submit"
                        class="btn btn-info"
                        style="color: white; font-weight: bold; width: 130px; height:50px; border-radius:12px; font-size: 21px;">
                    Predict
                </button>
            </div>
        </form>
        <center>
            {{result}}
        </center>
    </div>

</div>
<br><br><br><br><br><br><br><br><br>
<!-- Form section -->


{% endblock %}

templates/users/crop_recommendation.html
{% extends 'users/user_base.html' %}

{% block title %}
    User|| crop_recommendation
{% endblock %}
{% block crop_recommendation %}
    active
{% endblock %}

{% block content %}
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
 <section id="intro">

    <div class="intro-text">
<!--        <div class="container" style="margin-top:-200px;">-->
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br><br/><br/>
      <p><h3 align="center" style="color:green;font-weight:bold;">Crop_recommendation.csv</h3></p>
      <!--<a href="#about" class="btn-get-started scrollto">Get Started</a>-->
        <center>
        {{dat|safe}}
            </center>
    </div>
  </section>
{%endblock%}

templates/users/user_base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="shortcut icon" href="{% static 'images/favicon/crop.png' %}" type="image/x-icon">

    <!-- Css Link-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>
        {% block title %}{% endblock %}
    </title>

    <style>
        a {
            color: white
        }

        .active {
            color: #007bff;
        }

        .bg-light1 {
            background: #1b4670;
            color: White;

        }

        .btn:not(:disabled):not(.disabled) {
            background-color: #1b4670;

        }

        * {
            font-family: "Book Antiqua";
        }

    </style>


</head>
<body style="background:#E9ECEF;">
<!-- Navbar -->
<header>
    <nav class="navbar navbar-expand-lg fixed-top  bg-light1">

        <a class="navbar-brand" href="#">
            <img src="{% static 'images/crop.png' %}" alt="" width="10%" style="margin-top: -10px;">
            <span class="name pull-left">  CROP  </span>
        </a>


        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link {% block user_home %} {% endblock %}" href="/"> Home </a>#}-->
<!--                    </li>-->
                <li class="nav-item">
                    <a class="nav-link {% block  add_data %} {% endblock %}" href="{% url 'users_:add_data' %}"> Add
                        Data </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% block view_data %} {% endblock %}" href="{% url 'users_:view_data' %}">View
                        Data</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% block Ml_result %} {% endblock %}"
                       href="{% url 'users_:user_classification' %}">Ml_Algo's</a>
                </li>
            </ul>

            <button class="btn btn-outline-info my-2 my-sm-0" type="submit">
                <a href="{% url 'user_login' %}">Logout </a>
            </button>

        </div>
    </nav>

</header>
<br><br><br><br><br><br><br><br>
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
        <h1 style="color:teal; font-weight:bold;">Intelligent Crop Recommendation System using Machine Learning
            System</h1>
    </div>
</section>


{% block content %}

{% endblock %}


<!-- Footer -->

<footer class="page-footer font-small  bg-light1">
    <div class="footer-copyright text-center py-3">© 2022 Copyright:
        <a href="#"> CROP</a>
    </div>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/users/user_home.html
{% extends 'users/user_base.html' %}

{% block title %}
    User || Home
{% endblock %}

{% block user_home %}
    active
{% endblock %}
{% block content %}

    <section>

        <nav aria-label="breadcrumb">
            <br><br><br><br><br><br><br><br>

            <ol class="breadcrumb bg-info" style="color: white;">

                <li class="breadcrumb-item nav-link" aria-current="page">
                    {{ request.session.username|capfirst }} Here.
                </li>
            </ol>
            <br><br><br><br><br><br><br><br><br><br><br>
        </nav>

        <div class="jumbotron">
            <div class="container">
                <div class="row">
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/users/view_data.html
{% extends 'users/user_base.html' %}

{% block title %}
    User || view_data
{% endblock %}

{% block view_data %}
    active
{% endblock %}
{% block content %}

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
<section id="intro">
<h3 align="center" style="color:green;font-weight:bold;">Datasets Here are:</h3>
    <ol>
        <li><a href="{% url 'users_:crop_recommendation'  %}"style="color:green">Crop_Recommendation.csv</a></li>
        <li><a href="{% url 'users_:crop_sustainability3'  %}"style="color:green">Crop_Sustainability.csv</a></li>
    </ol>
  </section>
    <br><br><br><br><br><br><br><br>
{%endblock%}